### ISSUE TITLE
Vamos trabalhar juntos?

### ISSUE THREAD

**Issue by izaiasmachado** [matheus3301/ufc-pergamum-bot#1]
Olá Matheus, tudo bem?

Vi que você deu uma estrela no meu respositório de dados da UFC, muito obrigado!
Se quiser implementar o scraper do site da biblioteca seria muito legal, ai você só importa o [dados-ufc](https://github.com/izaiasmachado/dados-ufc) no seu projeto (já está publicado no NPM). Eu já tenho uma noção bem boa de como extrair os dados do [pergamum](https://pergamum.ufc.br/pergamum/biblioteca/index.php) mas ainda não tive tempo.

Sei que o meu projeto ainda está embrionário mas penso que ia ser muito bom para a comunidade acadêmica! 
Desde já agradeço pela atenção!

**Comment by matheus3301** [comment]
Opa Izaias, muito obrigado pela atenção. De fato, a biblioteca de dados está muito legal, seria muito massa implementar ela no projeto! Vamos trabalhar juntos sim, o projeto está bem no começo ainda, mas vejo bastante potencial na ferramenta, creio que juntos podemos fazer algo de valor para a comunidade. Bora trabalhar 😀
